version: 2.1

executors:
  docker_cimg_base:
    docker:
      - image: cimg/base:2023.02-20.04

jobs:
  step_1:
    executor: docker_cimg_base
    resource_class: small
    steps:
      - run:
          command: echo "step_1" > /tmp/step_1.md 
          working_directory: /tmp/repo
      - persist_to_workspace:
          root: /tmp
          paths:
            - step_1.md

  step_2:
    executor: docker_cimg_base
    resource_class: small
    steps:
      - attach_workspace:
          at: /root/circleci
      - run:
        command: cat /tmp/step_1.md
  
workflows:
  version: 2
  test_workflow:
    jobs:
      - step_1
      - step_2:
          requires:
            - step_1 
   
